# Generated by Django 4.2 on 2023-04-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('author', models.CharField(max_length=50, verbose_name='Author')),
                ('subtitle', models.CharField(max_length=300, verbose_name='Subtitle')),
                ('text', models.TextField(max_length=1000, verbose_name='Text')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
